import { writeFileSync } from 'node:fs';
const Ref=name=>({Ref:name}),GetAtt=(name,attr)=>({'Fn::GetAtt':[name,attr]}),Sub=text=>({'Fn::Sub':text});
const resources={
  Games:{Type:'AWS::DynamoDB::Table',DeletionPolicy:'Retain',UpdateReplacePolicy:'Retain',Properties:{BillingMode:'PAY_PER_REQUEST',AttributeDefinitions:[{AttributeName:'pk',AttributeType:'S'},{AttributeName:'sk',AttributeType:'S'},{AttributeName:'botPending',AttributeType:'S'}],KeySchema:[{AttributeName:'pk',KeyType:'HASH'},{AttributeName:'sk',KeyType:'RANGE'}],GlobalSecondaryIndexes:[{IndexName:'PendingBots',KeySchema:[{AttributeName:'botPending',KeyType:'HASH'}],Projection:{ProjectionType:'KEYS_ONLY'}}],PointInTimeRecoverySpecification:{PointInTimeRecoveryEnabled:true},SSESpecification:{SSEEnabled:true},TimeToLiveSpecification:{AttributeName:'ttl',Enabled:true},StreamSpecification:{StreamViewType:'NEW_AND_OLD_IMAGES'}}},
  HttpApi:{Type:'AWS::Serverless::HttpApi',Properties:{StageName:'$default',DefaultRouteSettings:{ThrottlingBurstLimit:20,ThrottlingRateLimit:10}}},
  Alerts:{Type:'AWS::SNS::Topic'},
  AlertEmail:{Type:'AWS::SNS::Subscription',Condition:'HasEmail',Properties:{TopicArn:Ref('Alerts'),Protocol:'email',Endpoint:Ref('AlertEmailAddress')}},
  DeadLetters:{Type:'AWS::SQS::Queue',Properties:{MessageRetentionPeriod:1209600,SqsManagedSseEnabled:true}},
};

resources.UserPool={Type:'AWS::Cognito::UserPool',DeletionPolicy:'Retain',UpdateReplacePolicy:'Retain',Properties:{AdminCreateUserConfig:{AllowAdminCreateUserOnly:true},UsernameAttributes:['email'],UsernameConfiguration:{CaseSensitive:false},AutoVerifiedAttributes:['email'],UserPoolTier:'LITE',Policies:{PasswordPolicy:{MinimumLength:12,RequireLowercase:true,RequireUppercase:true,RequireNumbers:true,RequireSymbols:true,TemporaryPasswordValidityDays:7}},AccountRecoverySetting:{RecoveryMechanisms:[{Name:'verified_email',Priority:1}]}}};
resources.PlayScope={Type:'AWS::Cognito::UserPoolResourceServer',Properties:{UserPoolId:Ref('UserPool'),Identifier:'wordboogie',Name:'WordBoogie',Scopes:[{ScopeName:'play',ScopeDescription:'Access approved-player games'}]}};
resources.WebClient={Type:'AWS::Cognito::UserPoolClient',DependsOn:'PlayScope',Properties:{UserPoolId:Ref('UserPool'),GenerateSecret:false,SupportedIdentityProviders:['COGNITO'],AllowedOAuthFlowsUserPoolClient:true,AllowedOAuthFlows:['code'],AllowedOAuthScopes:['openid','wordboogie/play'],CallbackURLs:[Sub('${FrontendUrl}/')],LogoutURLs:[Sub('${FrontendUrl}/')],PreventUserExistenceErrors:'ENABLED',EnableTokenRevocation:true,AccessTokenValidity:5,IdTokenValidity:5,RefreshTokenValidity:1,TokenValidityUnits:{AccessToken:'minutes',IdToken:'minutes',RefreshToken:'days'},ExplicitAuthFlows:['ALLOW_REFRESH_TOKEN_AUTH']}};
resources.LoginDomain={Type:'AWS::Cognito::UserPoolDomain',Properties:{UserPoolId:Ref('UserPool'),Domain:Sub('${LoginDomainPrefix}-${AWS::AccountId}-${AWS::Region}')}};
const issuer=Sub('https://cognito-idp.${AWS::Region}.${AWS::URLSuffix}/${UserPool}');
resources.HttpApi.Properties.Auth={DefaultAuthorizer:'ApprovedPlayers',Authorizers:{ApprovedPlayers:{IdentitySource:'$request.header.Authorization',JwtConfiguration:{issuer,audience:[Ref('WebClient')]},AuthorizationScopes:['wordboogie/play']}}};
const urlParts={'Fn::Split':['/',Ref('FrontendUrl')]};
resources.HttpApi.Properties.CorsConfiguration={AllowOrigins:[{'Fn::Join':['/',[{'Fn::Select':[0,urlParts]},{'Fn::Select':[1,urlParts]},{'Fn::Select':[2,urlParts]}]]}],AllowMethods:['GET','POST','PATCH','OPTIONS'],AllowHeaders:['Content-Type','Authorization','X-Game-Token'],MaxAge:600};

const tablePolicy={Effect:'Allow',Action:['dynamodb:GetItem','dynamodb:Query','dynamodb:PutItem','dynamodb:UpdateItem','dynamodb:ConditionCheckItem'],Resource:GetAtt('Games','Arn')};
const common={Runtime:'nodejs24.x',Architectures:['arm64'],CodeUri:'../dist/lambda/',MemorySize:512,Timeout:30,Environment:{Variables:{TABLE_NAME:Ref('Games'),FRONTEND_URL:Ref('FrontendUrl'),AUTH_ISSUER:issuer,AUTH_CLIENT_ID:Ref('WebClient')}},Tracing:'PassThrough'};
resources.ApiFunction={Type:'AWS::Serverless::Function',Properties:{...common,Handler:'services/hosted/handler.handler',ReservedConcurrentExecutions:{'Fn::If':['LimitConcurrencyEnabled',5,Ref('AWS::NoValue')]},Policies:[{Statement:[tablePolicy]}],Events:Object.fromEntries([
 ['Health','GET','/health'],['Create','POST','/games'],['ResolveInvite','POST','/invites/resolve'],['Snapshot','GET','/games/{id}'],['History','GET','/games/{id}/history'],['Join','POST','/games/{id}/join'],['Lobby','PATCH','/games/{id}/lobby'],['RotateInvite','POST','/games/{id}/invite'],['Start','POST','/games/{id}/start'],['Action','POST','/games/{id}/actions']
].map(([name,method,path])=>[name,{Type:'HttpApi',Properties:{ApiId:Ref('HttpApi'),Path:path,Method:method,...(name==='Health'?{Auth:{Authorizer:'NONE'}}:{})}}]))}};
resources.BotFunction={Type:'AWS::Serverless::Function',Properties:{...common,Handler:'services/hosted/handler.worker',Timeout:60,ReservedConcurrentExecutions:{'Fn::If':['LimitConcurrencyEnabled',2,Ref('AWS::NoValue')]},Policies:[{Statement:[tablePolicy,{Effect:'Allow',Action:['dynamodb:BatchWriteItem'],Resource:GetAtt('Games','Arn')},{Effect:'Allow',Action:['dynamodb:Query'],Resource:Sub('${Games.Arn}/index/PendingBots')},{Effect:'Allow',Action:['sqs:SendMessage'],Resource:GetAtt('DeadLetters','Arn')}]}],Events:{Recovery:{Type:'Schedule',Properties:{Schedule:'rate(5 minutes)'}},Changes:{Type:'DynamoDB',Properties:{Stream:GetAtt('Games','StreamArn'),StartingPosition:'TRIM_HORIZON',BatchSize:1,MaximumRetryAttempts:10,MaximumRecordAgeInSeconds:86400,BisectBatchOnFunctionError:true,DestinationConfig:{OnFailure:{Type:'SQS',Destination:GetAtt('DeadLetters','Arn')}},FilterCriteria:{Filters:[{Pattern:JSON.stringify({dynamodb:{Keys:{sk:{S:['STATE']}}}})}]}}}}}};
for(const name of ['ApiFunction','BotFunction']) {
  resources[`${name}Logs`]={Type:'AWS::Logs::LogGroup',Properties:{LogGroupName:Sub(`/aws/lambda/\${${name}}`),RetentionInDays:14}};
  resources[`${name}Errors`]={Type:'AWS::CloudWatch::Alarm',Properties:{Namespace:'AWS/Lambda',MetricName:'Errors',Dimensions:[{Name:'FunctionName',Value:Ref(name)}],Statistic:'Sum',Period:300,EvaluationPeriods:1,Threshold:1,ComparisonOperator:'GreaterThanOrEqualToThreshold',TreatMissingData:'notBreaching',AlarmActions:[Ref('Alerts')]}};
}
resources.WorkerLag={Type:'AWS::CloudWatch::Alarm',Properties:{Namespace:'AWS/Lambda',MetricName:'IteratorAge',Dimensions:[{Name:'FunctionName',Value:Ref('BotFunction')}],Statistic:'Maximum',Period:300,EvaluationPeriods:1,Threshold:60000,ComparisonOperator:'GreaterThanThreshold',TreatMissingData:'notBreaching',AlarmActions:[Ref('Alerts')]}};
resources.DeadLetterAlarm={Type:'AWS::CloudWatch::Alarm',Properties:{Namespace:'AWS/SQS',MetricName:'ApproximateNumberOfMessagesVisible',Dimensions:[{Name:'QueueName',Value:GetAtt('DeadLetters','QueueName')}],Statistic:'Maximum',Period:300,EvaluationPeriods:1,Threshold:1,ComparisonOperator:'GreaterThanOrEqualToThreshold',TreatMissingData:'notBreaching',AlarmActions:[Ref('Alerts')]}};
resources.Budget={Type:'AWS::Budgets::Budget',Condition:'HasEmail',Properties:{Budget:{BudgetName:Sub('${AWS::StackName}-monthly'),BudgetType:'COST',TimeUnit:'MONTHLY',BudgetLimit:{Amount:Ref('MonthlyBudget'),Unit:'USD'}},NotificationsWithSubscribers:[{Notification:{NotificationType:'ACTUAL',ComparisonOperator:'GREATER_THAN',Threshold:80,ThresholdType:'PERCENTAGE'},Subscribers:[{SubscriptionType:'EMAIL',Address:Ref('AlertEmailAddress')}]}]}};
const template={AWSTemplateFormatVersion:'2010-09-09',Transform:'AWS::Serverless-2016-10-31',Description:'WordBoogie serverless API and persistent background bots',Parameters:{LoginDomainPrefix:{Type:'String',Default:'wordboogie',AllowedPattern:'[a-z0-9]([a-z0-9-]{0,30}[a-z0-9])?',Description:'Unique login domain prefix, suffixed with account and region'},LimitConcurrency:{Type:'String',Default:'true',AllowedValues:['true','false'],Description:'Reserve/cap Lambda concurrency; disable only when account quota cannot accommodate it'},FrontendUrl:{Type:'String',AllowedPattern:'https://[a-zA-Z0-9.-]+(/[a-zA-Z0-9._~-]+)*',Description:'Full Pages URL including repository path, without trailing slash'},AlertEmailAddress:{Type:'String',Default:'',Description:'Optional budget and operations notification email'},MonthlyBudget:{Type:'Number',Default:5,MinValue:1,Description:'Account-wide monthly budget notification threshold in USD; not a spending cap'}},Conditions:{LimitConcurrencyEnabled:{'Fn::Equals':[Ref('LimitConcurrency'),'true']},HasEmail:{'Fn::Not':[{'Fn::Equals':[Ref('AlertEmailAddress'),'']}]}},Resources:resources,Outputs:{UserPoolId:{Value:Ref('UserPool')},AuthClientId:{Value:Ref('WebClient')},AuthDomain:{Value:Sub('https://${LoginDomainPrefix}-${AWS::AccountId}-${AWS::Region}.auth.${AWS::Region}.amazoncognito.com')},AuthIssuer:{Value:issuer},ApiUrl:{Value:Sub('https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}')},TableName:{Value:Ref('Games')},WorkerFunctionName:{Value:Ref('BotFunction')},DeadLetterQueueUrl:{Value:Ref('DeadLetters')}}};
writeFileSync(new URL('./template.json',import.meta.url),JSON.stringify(template,null,2)+'\n');
console.log('Generated infra/template.json');

